server:
  extraArgs:
    - --insecure 
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostname: argocd.eks.mohamedhassanproject.com
    tls: true
    extraTls:
      - secretName: argocd-ingress-tls
        hosts:
          - argocd.eks.mohamedhassanproject.com